version: '2'
services:
    src:
        image: busybox
        volumes:
            - ./:/srv:rw

    mysql:
        image: mysql:5 #mysql:latest
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_VERBOSE: database
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: password
        ports:
            - "8080:80"

    mongo:
        image: mongo:3.0 #mongo:latest
        volumes:
            - ./docker/mongo:/data/db

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - "8081:8081"

    symfony:
        build:
            context: docker/symfony/
            args:
                GITHUB_ACCESS_TOKEN:
                VENDOR_NAME:
                BUNDLE_NAME:
                BUNDLE_FORMAT:
        env_file: .env
        volumes:
            - ./docker/symfony/php.ini:/usr/local/etc/php/php.ini

    php-fpm:
        build: docker/php-fpm/
        volumes:
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

    nginx:
        image: nginx
        command: ["nginx", "-g", "daemon off;"]
        entrypoint: docker-entrypoint
        environment:
            OPENSSL_DAYS:
            OPENSSL_NEWKEY:
            OPENSSL_SUBJ_C:
            OPENSSL_SUBJ_ST:
            OPENSSL_SUBJ_L:
            OPENSSL_SUBJ_O:
            OPENSSL_SUBJ_OU:
            OPENSSL_SUBJ_CN:
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/docker-entrypoint:/usr/local/bin/docker-entrypoint
        ports:
            - "80:80"
            - "443:443"

    phpunit:
        build: docker/phpunit/
        env_file: .env
        working_dir: /srv/symfony
        command: ["phpunit", "src/$VENDOR_NAME/$BUNDLE_NAME/Tests"]
