version: '2'
services:
    src:
        extends:
            file: common-services.yml
            service: src

    # mysql:
    #     extends:
    #         file: common-services.yml
    #         service: mysql
    #     # uncomment to access from outside of the container
    #     # ports:
    #     #     - "3306:3306"

    # # uncommnet for phpmyadmin client
    # phpmyadmin:
    #     extends:
    #         file: common-services.yml
    #         service: phpmyadmin
    #     depends_on:
    #         - mysql

    # mongo:
    #     extends:
    #         file: common-services.yml
    #         service: mongo
    #     #uncomment to access from outside of the container
    #     # ports:
    #     #     - "27017:27017"

    # # uncommnet for web mongo client
    # mongo-express:
    #     extends:
    #         file: common-services.yml
    #         service: mongo-express
    #     depends_on:
    #         - mongo

    symfony:
        extends:
            file: common-services.yml
            service: symfony
        depends_on:
            - src
            # - mongo
            # - mysql
        volumes_from:
            - src
